### ISSUE TITLE
[BUG] The straw golem stops doing tasks after a single task.

### ISSUE THREAD

**Issue by KingKobold21** [HeroBrianMack/strawgolem#1]
**Describe the bug**
When the straw golem is placed, he will seek out the nearest crop to harvest. However, he will pick it up, and start wandering off, despite chests being nearby. If I use the Carry On Mod to pick him up and pout him back down, it seems to "reset" him for a single task, as he will take the thing he has harvested and place it in a nearby chest, then continue to wander around doing nothing. During this wandering, he also does not follow any other set programming; i.e. He will not avoid players, monsters, or raiders, he does not panic when attacked, no shivering or anything else. 

**To Reproduce**
1. Create the golem next to the farm field.
2. Watch him grab a single crop.
3. He then wanders off and does nothing.

**Expected behavior**
He grabs a crop, brings it to a nearby chest, and repeats until there are no more crops left to grab.

**Desktop (please complete the following information):**
Haybale Version: Forge-1.20.1-1.0.0
Strawgolem Version:forge-1.20.1-3.0.1

**Comment by HeroBrianMack** [comment]
This should be improved if not fixed in version 3.0.2, let me know if the AI has improved with that!
